## Sample is the name of the file that you want to carry through.
## If the sample name is bob, then all of the files created from this pipeline
## would have "bob" as the prefix.
## i.e bob_homepage.html, bob_high_and_moderate_SNPs, bob_gene2gene_results.txt

## Make sure to change all of these paths to point to the location of these files on YOUR device
samples:
  bevCombind:

vcf_path: data/

vcf_ext: .vcf

bed_file: data/bevCombind_cnv.bed

references: data/ref-data/human_g1k_v37.fasta

database: data/endpoints/new.sqlite

lua: data/ref-data/rare_disease.lua

temppath: data/ref-data/

fai: data/ref-data/genome.fa.fai

chromosome_file_path: data/ref-data/

endpoints_folder: data/endpoints/

scripts: src/scripts/

project_summary: project_summary.txt

size_cutoff: 1000
